# Generated by Django 6.0.4 on 2026-04-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lata',
            fields=[
                ('id_lata', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descontinuada', models.BooleanField(default=False)),
                ('disponivel_portugal', models.BooleanField(default=True)),
                ('notas', models.TextField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lata.marca')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lata.tamanho')),
            ],
        ),
    ]
